// app/pages/auth/register.vue
<script setup lang="ts">
import { z } from "zod"

const toast = useToast()

const schema = z
	.object({
		email: z.email("Invalid email"),
		password: z.string().min(8, "Password should be at least 8 characters"),
		passwordConfirm: z.string(),
		userName: z.string().min(3, "User Name should be at least 3 characters"),
	})
	.refine((data) => data.password === data.passwordConfirm, {
		message: "Passwords don't match",
		path: ["passwordConfirm"],
	})

type Schema = z.output<typeof schema>

const state = reactive<Partial<Schema>>({
	email: "",
	password: "",
	passwordConfirm: "",
	userName: "",
})

// -------------------------------------------------------------------------------

const register = async () => {
	try {
		if (!state.email || !state.password) {
			toast.add({
				title: "Error",
				description: "Email and Password are required",
				color: "error",
			})
			throw new Error("Invalid email or password format")
		}

		await pb.collection("users").create({
			email: state.email,
			password: state.password,
			passwordConfirm: state.passwordConfirm,
			name: state.userName,
		})

		await pb.collection("users").authWithPassword(state.email, state.password)
		navigateTo("/dashboard")

		useToast().add({
			title: "Registration successful",
			color: "success",
		})
	} catch (error) {
		toast.add({
			title: "Error",
			description: "Something went wrong",
			color: "error",
		})
		console.log(error)
	}
}

// -------------------------------------------------------------------------------

defineShortcuts({
	meta_o: () => fillRegisterForm(state),
})
</script>

<template>
	<MaxContainer>
		<UCard class="m-auto w-full max-w-md p-6" variant="subtle">
			<UForm
				class="grid grid-cols-[18em] align-middle justify-center space-y-4 m-auto"
				:state="state"
				:schema="schema"
				@submit="register"
			>
				<h1 class="font-bold text-2xl">Create your Account</h1>
				<UFormField name="email">
					<UInput
						v-model="state.email"
						class="w-full"
						type="email"
						placeholder="E-Mail"
						size="xl"
					/>
				</UFormField>
				<UFormField name="userName">
					<UInput
						v-model="state.userName"
						type="text"
						placeholder="Your Name"
						size="xl"
						class="w-full"
					/>
				</UFormField>
				<UFormField name="password">
					<UInput
						v-model="state.password"
						type="password"
						placeholder="Password"
						size="xl"
						class="w-full"
					/>
				</UFormField>
				<UFormField name="passwordConfirm">
					<UInput
						v-model="state.passwordConfirm"
						type="password"
						placeholder="Confirm Password"
						size="xl"
						class="w-full"
					/>
				</UFormField>

				<UButton type="submit" color="primary" size="xl">Register</UButton>

				<USeparator />

				<p>Or register with an Account</p>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:apple" />Register with Apple</UButton
				>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:google" />Register with Google</UButton
				>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:github" />Register with Github</UButton
				>

				<USeparator />

				<p>
					Already have an Account?
					<NuxtLink to="/auth/login" class="text-purpleish-500">Log in</NuxtLink>
				</p>
			</UForm>
		</UCard>
	</MaxContainer>
</template>

// src/app/pages/auth/register/register.component.ts
import { Component, HostListener } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { RouterLink } from '@angular/router'
import { z } from 'zod'
import { AuthService } from '../../../core/services/auth.service'
import { MaxContainerComponent } from '../../../shared/components/max-container.component'
import { ToastService } from '../../../core/services/toast.service'
import { fillRegisterForm } from '../../../shared/utils/fill-register'

const schema = z
  .object({
    email: z.string().email('Invalid email'),
    password: z.string().min(8, 'Password should be at least 8 characters'),
    passwordConfirm: z.string(),
  })
  .refine((data) => data.password === data.passwordConfirm, {
    message: "Passwords don't match",
    path: ['passwordConfirm'],
  })

type Schema = z.output<typeof schema>

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, RouterLink, MaxContainerComponent],
  template: `
    <app-max-container>
      <div class="m-auto w-full max-w-md">
        <div class="card p-6">
          <form class="space-y-4" (ngSubmit)="register()">
            <h1 class="text-2xl font-bold">Create your Account</h1>
            <input
              class="input"
              type="email"
              name="email"
              placeholder="E-Mail"
              [(ngModel)]="state.email"
              required
            />
            <input
              class="input"
              type="password"
              name="password"
              placeholder="Password"
              [(ngModel)]="state.password"
              required
            />
            <input
              class="input"
              type="password"
              name="passwordConfirm"
              placeholder="Confirm Password"
              [(ngModel)]="state.passwordConfirm"
              required
            />
            <button class="btn btn-primary w-full" type="submit">Register</button>

            <div class="border-t border-slate-200 pt-4">
              <p class="text-sm text-slate-500">Or register with an Account</p>
              <div class="mt-3 grid gap-2">
                <button class="btn btn-outline" type="button">Register with Apple</button>
                <button class="btn btn-outline" type="button">Register with Google</button>
                <button class="btn btn-outline" type="button">Register with Github</button>
              </div>
            </div>

            <p class="text-sm text-slate-600">
              Already have an Account?
              <a class="text-indigo-500" routerLink="/auth/login">Log in</a>
            </p>
          </form>
        </div>
      </div>
    </app-max-container>
  `,
})
export class RegisterComponent {
  state: Partial<Schema> = {
    email: '',
    password: '',
    passwordConfirm: '',
  }

  constructor(private auth: AuthService, private toast: ToastService) {}

  @HostListener('document:keydown', ['$event'])
  handleShortcut(event: KeyboardEvent) {
    if (event.metaKey && event.key.toLowerCase() === 'o') {
      event.preventDefault()
      fillRegisterForm(this.state)
    }
  }

  async register() {
    const result = schema.safeParse(this.state)
    if (!result.success) {
      this.toast.add({
        title: 'Registration failed',
        description: result.error.issues[0]?.message,
        color: 'error',
      })
      return
    }

    await this.auth.register(
      result.data.email,
      result.data.password,
      result.data.passwordConfirm,
    )
  }
}
