// app/pages/login.vue
<script setup lang="ts">
import * as z from "zod"

const schema = z.object({
	email: z.email("invalid email"),
	password: z.string().min(8, "Password should be at least 8 characters "),
})

type Schema = z.output<typeof schema>

const state = reactive<Partial<Schema>>({
	email: "",
	password: "",
})

// ------------------------------------------------------------------------------

const login = async () => {
	try {
		if (typeof state.email !== "string" || typeof state.password !== "string") {
			throw new TypeError("Invalid email or password format")
		}
		await pb.collection("users").authWithPassword(state.email, state.password)
		navigateTo("/dashboard")

		useToast().add({
			title: "Login successful",
			color: "success",
		})
	} catch {
		errorToast("Login failed, please check your credentials and try again.")
	}
}
</script>

<template>
	<MaxContainer>
		<UCard class="m-auto w-full max-w-md p-6" variant="subtle">
			<UForm
				class="grid grid-cols-[18em] align-middle justify-center space-y-4 m-auto"
				:state="state"
				:schema="schema"
				@submit="login"
			>
				<h1 class="font-bold text-2xl">Log in with your Email</h1>
				<UFormField name="email">
					<UInput
						v-model="state.email"
						class="w-full"
						type="email"
						placeholder="E-Mail"
						size="xl"
					/>
				</UFormField>
				<UFormField name="password">
					<UInput
						v-model="state.password"
						type="password"
						placeholder="Password"
						size="xl"
						class="w-full"
					/>
				</UFormField>
				<UButton type="submit" color="primary" size="xl">Log in</UButton>

				<USeparator />

				<p>Or log in with an existing Account</p>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:apple" />Log in with Apple</UButton
				>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:google" />Log in with Google</UButton
				>
				<UButton variant="outline" size="xl"
					><Icon size="20" name="uil:github" />Log in with Github</UButton
				>

				<USeparator />

				<p>
					Dont have an Account?
					<NuxtLink to="/register" class="text-purpleish-500">Register Now</NuxtLink>
				</p>
			</UForm>
		</UCard>
	</MaxContainer>
</template>

// src/app/pages/auth/login/login.component.ts
import { Component } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { RouterLink } from '@angular/router'
import { z } from 'zod'
import { AuthService } from '../../../core/services/auth.service'
import { MaxContainerComponent } from '../../../shared/components/max-container.component'
import { ToastService } from '../../../core/services/toast.service'

const schema = z.object({
  email: z.string().email('Invalid email'),
  password: z.string().min(8, 'Password should be at least 8 characters'),
})

type Schema = z.output<typeof schema>

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, RouterLink, MaxContainerComponent],
  template: `
    <app-max-container>
      <div class="m-auto w-full max-w-md">
        <div class="card p-6">
          <form class="space-y-4" (ngSubmit)="login()">
            <h1 class="text-2xl font-bold">Log in with your Email</h1>
            <input
              class="input"
              type="email"
              name="email"
              placeholder="E-Mail"
              [(ngModel)]="state.email"
              required
            />
            <input
              class="input"
              type="password"
              name="password"
              placeholder="Password"
              [(ngModel)]="state.password"
              required
            />
            <button class="btn btn-primary w-full" type="submit">Log in</button>

            <div class="border-t border-slate-200 pt-4">
              <p class="text-sm text-slate-500">Or log in with an existing Account</p>
              <div class="mt-3 grid gap-2">
                <button class="btn btn-outline" type="button">Log in with Apple</button>
                <button class="btn btn-outline" type="button">Log in with Google</button>
                <button class="btn btn-outline" type="button">Log in with Github</button>
              </div>
            </div>

            <p class="text-sm text-slate-600">
              Dont have an Account?
              <a class="text-indigo-500" routerLink="/auth/register">Register Now</a>
            </p>
          </form>
        </div>
      </div>
    </app-max-container>
  `,
})
export class LoginComponent {
  state: Partial<Schema> = {
    email: '',
    password: '',
  }

  constructor(private auth: AuthService, private toast: ToastService) {}

  async login() {
    const result = schema.safeParse(this.state)
    if (!result.success) {
      this.toast.add({
        title: 'Login failed',
        description: result.error.issues[0]?.message,
        color: 'error',
      })
      return
    }

    await this.auth.login(result.data.email, result.data.password)
  }
}
